version: '3.5'

services:
  local-postgres:
    image: postgres
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5332:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - main_network




networks:
  main_network:
    name: local-server
    driver: bridge