version: '3.5'

services:
  local-postgres:
    image: postgres
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5332:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - main_network

  local-mariadb:
    image: mariadb:10.2
    container_name: local-mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3406:3306'
    volumes:
      - .data/mariadb:/var/lib/mysql
    networks:
      - main_network
    environment:
      MYSQL_ROOT_PASSWORD: password

  local-mysql:
    image: mysql:5.7.33
    container_name: local-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3206:3306'
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - main_network
    environment:
      MYSQL_ROOT_PASSWORD: password

  local-redis:
    image: redis:6.0.6
    container_name: local-redis
    ports:
      - '6479:6379'
    # restart: always
    networks:
      - main_network

networks:
  main_network:
    name: local-server
    driver: bridge