version: '3.5'

services:
  local-postgres:
    image: postgres
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5332:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - main_network

  local-mariadb:
    image: mariadb:10.2
    container_name: local-mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3406:3306'
    volumes:
      - .data/mariadb:/var/lib/mysql
    networks:
      - main_network
    environment:
      MYSQL_ROOT_PASSWORD: password

  local-mysql:
    image: mysql:5.7.33
    container_name: local-mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - '3206:3306'
    volumes:
      - .data/mysql:/var/lib/mysql
    networks:
      - main_network
    environment:
      MYSQL_ROOT_PASSWORD: password

  local-redis:
    image: redis:6.0.6
    container_name: local-redis
    ports:
      - '6479:6379'
    # restart: always
    networks:
      - main_network

  local-rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: local-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - .data/rabbitmq-data:/var/lib/rabbitmq/
      - .data/rabbitmq-log:/var/log/rabbitmq/
    networks:
      - main_network

  local-nats:
    image: nats
    container_name: local-nats
    command: "--user nats --pass secret --http_port 8222 --debug=true --trace=true"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    # hostname: local-nats
    networks:
      - main_network

networks:
  main_network:
    name: local-server
    driver: bridge